version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core:latest
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "5000-5010:5000-5010"
    volumes:
      - ./config/:/etc/v2ray/
    command: ["run", "-config=/etc/v2ray/config.json"]

