# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dispatcher/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61pp/dispatcher/config.proto\x12\x19v2ray.core.app.dispatcher\"\x15\n\rSessionConfigJ\x04\x08\x01\x10\x02\"D\n\x06\x43onfig\x12:\n\x08settings\x18\x01 \x01(\x0b\x32(.v2ray.core.app.dispatcher.SessionConfigBl\n\x1d\x63om.v2ray.core.app.dispatcherP\x01Z-github.com/v2fly/v2ray-core/v5/app/dispatcher\xaa\x02\x19V2Ray.Core.App.Dispatcherb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.dispatcher.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.v2ray.core.app.dispatcherP\001Z-github.com/v2fly/v2ray-core/v5/app/dispatcher\252\002\031V2Ray.Core.App.Dispatcher'
  _globals['_SESSIONCONFIG']._serialized_start=58
  _globals['_SESSIONCONFIG']._serialized_end=79
  _globals['_CONFIG']._serialized_start=81
  _globals['_CONFIG']._serialized_end=149
# @@protoc_insertion_point(module_scope)
