# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/observatory/command/command.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2
from app.observatory import config_pb2 as app_dot_observatory_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%app/observatory/command/command.proto\x12\"v2ray.core.app.observatory.command\x1a common/protoext/extensions.proto\x1a\x1c\x61pp/observatory/config.proto\"\'\n\x18GetOutboundStatusRequest\x12\x0b\n\x03Tag\x18\x01 \x01(\t\"Z\n\x19GetOutboundStatusResponse\x12=\n\x06status\x18\x01 \x01(\x0b\x32-.v2ray.core.app.observatory.ObservationResult\"(\n\x06\x43onfig:\x1e\x82\xb5\x18\x1a\n\x0bgrpcservice\x12\x0bobservatory2\xa9\x01\n\x12ObservatoryService\x12\x92\x01\n\x11GetOutboundStatus\x12<.v2ray.core.app.observatory.command.GetOutboundStatusRequest\x1a=.v2ray.core.app.observatory.command.GetOutboundStatusResponse\"\x00\x42\x87\x01\n&com.v2ray.core.app.observatory.commandP\x01Z6github.com/v2fly/v2ray-core/v5/app/observatory/command\xaa\x02\"V2Ray.Core.App.Observatory.Commandb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.observatory.command.command_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.v2ray.core.app.observatory.commandP\001Z6github.com/v2fly/v2ray-core/v5/app/observatory/command\252\002\"V2Ray.Core.App.Observatory.Command'
  _globals['_CONFIG']._options = None
  _globals['_CONFIG']._serialized_options = b'\202\265\030\032\n\013grpcservice\022\013observatory'
  _globals['_GETOUTBOUNDSTATUSREQUEST']._serialized_start=141
  _globals['_GETOUTBOUNDSTATUSREQUEST']._serialized_end=180
  _globals['_GETOUTBOUNDSTATUSRESPONSE']._serialized_start=182
  _globals['_GETOUTBOUNDSTATUSRESPONSE']._serialized_end=272
  _globals['_CONFIG']._serialized_start=274
  _globals['_CONFIG']._serialized_end=314
  _globals['_OBSERVATORYSERVICE']._serialized_start=317
  _globals['_OBSERVATORYSERVICE']._serialized_end=486
# @@protoc_insertion_point(module_scope)
