# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/tls/utls/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2
from transport.internet.tls import config_pb2 as transport_dot_internet_dot_tls_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(transport/internet/tls/utls/config.proto\x12&v2ray.core.transport.internet.tls.utls\x1a common/protoext/extensions.proto\x1a#transport/internet/tls/config.proto\"\xc9\x01\n\x06\x43onfig\x12=\n\ntls_config\x18\x01 \x01(\x0b\x32).v2ray.core.transport.internet.tls.Config\x12\x0f\n\x07imitate\x18\x02 \x01(\t\x12\r\n\x05noSNI\x18\x03 \x01(\x08\x12\x46\n\nforce_alpn\x18\x04 \x01(\x0e\x32\x32.v2ray.core.transport.internet.tls.utls.ForcedALPN:\x18\x82\xb5\x18\x14\n\x08security\x12\x04utls\x90\xff)\x01*R\n\nForcedALPN\x12&\n\"TRANSPORT_PREFERENCE_TAKE_PRIORITY\x10\x00\x12\x0b\n\x07NO_ALPN\x10\x01\x12\x0f\n\x0bUTLS_PRESET\x10\x02\x42\x93\x01\n*com.v2ray.core.transport.internet.tls.utlsP\x01Z:github.com/v2fly/v2ray-core/v5/transport/internet/tls/utls\xaa\x02&V2Ray.Core.Transport.Internet.Tls.UTlsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.tls.utls.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*com.v2ray.core.transport.internet.tls.utlsP\001Z:github.com/v2fly/v2ray-core/v5/transport/internet/tls/utls\252\002&V2Ray.Core.Transport.Internet.Tls.UTls'
  _globals['_CONFIG']._options = None
  _globals['_CONFIG']._serialized_options = b'\202\265\030\024\n\010security\022\004utls\220\377)\001'
  _globals['_FORCEDALPN']._serialized_start=359
  _globals['_FORCEDALPN']._serialized_end=441
  _globals['_CONFIG']._serialized_start=156
  _globals['_CONFIG']._serialized_end=357
# @@protoc_insertion_point(module_scope)
