# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/request/stereotype/meek/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7transport/internet/request/stereotype/meek/config.proto\x12\x35v2ray.core.transport.internet.request.stereotype.meek\x1a common/protoext/extensions.proto\"0\n\x06\x43onfig\x12\x0b\n\x03url\x18\x01 \x01(\t:\x19\x82\xb5\x18\x15\n\ttransport\x12\x04meek\x90\xff)\x01\x42\xc0\x01\n9com.v2ray.core.transport.internet.request.stereotype.meekP\x01ZIgithub.com/v2fly/v2ray-core/v5/transport/internet/request/stereotype/meek\xaa\x02\x35V2Ray.Core.Transport.Internet.Request.Stereotype.Meekb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.request.stereotype.meek.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n9com.v2ray.core.transport.internet.request.stereotype.meekP\001ZIgithub.com/v2fly/v2ray-core/v5/transport/internet/request/stereotype/meek\252\0025V2Ray.Core.Transport.Internet.Request.Stereotype.Meek'
  _globals['_CONFIG']._options = None
  _globals['_CONFIG']._serialized_options = b'\202\265\030\025\n\ttransport\022\004meek\220\377)\001'
  _globals['_CONFIG']._serialized_start=148
  _globals['_CONFIG']._serialized_end=196
# @@protoc_insertion_point(module_scope)
