# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/quic/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from common.protocol import headers_pb2 as common_dot_protocol_dot_headers__pb2
from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$transport/internet/quic/config.proto\x12\"v2ray.core.transport.internet.quic\x1a\x19google/protobuf/any.proto\x1a\x1d\x63ommon/protocol/headers.proto\x1a common/protoext/extensions.proto\"\x90\x01\n\x06\x43onfig\x12\x0b\n\x03key\x18\x01 \x01(\t\x12<\n\x08security\x18\x02 \x01(\x0b\x32*.v2ray.core.common.protocol.SecurityConfig\x12$\n\x06header\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any:\x15\x82\xb5\x18\x11\n\ttransport\x12\x04quicB\x87\x01\n&com.v2ray.core.transport.internet.quicP\x01Z6github.com/v2fly/v2ray-core/v5/transport/internet/quic\xaa\x02\"V2Ray.Core.Transport.Internet.Quicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.quic.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.v2ray.core.transport.internet.quicP\001Z6github.com/v2fly/v2ray-core/v5/transport/internet/quic\252\002\"V2Ray.Core.Transport.Internet.Quic'
  _globals['_CONFIG']._options = None
  _globals['_CONFIG']._serialized_options = b'\202\265\030\021\n\ttransport\022\004quic'
  _globals['_CONFIG']._serialized_start=169
  _globals['_CONFIG']._serialized_end=313
# @@protoc_insertion_point(module_scope)
