# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/blackhole/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproxy/blackhole/config.proto\x12\x1av2ray.core.proxy.blackhole\x1a\x19google/protobuf/any.proto\x1a common/protoext/extensions.proto\"\x0e\n\x0cNoneResponse\"\x0e\n\x0cHTTPResponse\"0\n\x06\x43onfig\x12&\n\x08response\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"-\n\x10SimplifiedConfig:\x19\x82\xb5\x18\x15\n\x08outbound\x12\tblackholeBo\n\x1e\x63om.v2ray.core.proxy.blackholeP\x01Z.github.com/v2fly/v2ray-core/v5/proxy/blackhole\xaa\x02\x1aV2Ray.Core.Proxy.Blackholeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy.blackhole.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.v2ray.core.proxy.blackholeP\001Z.github.com/v2fly/v2ray-core/v5/proxy/blackhole\252\002\032V2Ray.Core.Proxy.Blackhole'
  _globals['_SIMPLIFIEDCONFIG']._options = None
  _globals['_SIMPLIFIEDCONFIG']._serialized_options = b'\202\265\030\025\n\010outbound\022\tblackhole'
  _globals['_NONERESPONSE']._serialized_start=121
  _globals['_NONERESPONSE']._serialized_end=135
  _globals['_HTTPRESPONSE']._serialized_start=137
  _globals['_HTTPRESPONSE']._serialized_end=151
  _globals['_CONFIG']._serialized_start=153
  _globals['_CONFIG']._serialized_end=201
  _globals['_SIMPLIFIEDCONFIG']._serialized_start=203
  _globals['_SIMPLIFIEDCONFIG']._serialized_end=248
# @@protoc_insertion_point(module_scope)
