# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/observatory/burst/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"app/observatory/burst/config.proto\x12 v2ray.core.app.observatory.burst\x1a common/protoext/extensions.proto\"\x8c\x01\n\x06\x43onfig\x12\x18\n\x10subject_selector\x18\x02 \x03(\t\x12G\n\x0bping_config\x18\x03 \x01(\x0b\x32\x32.v2ray.core.app.observatory.burst.HealthPingConfig:\x1f\x82\xb5\x18\x1b\n\x07service\x12\x10\x62urstObservatory\"w\n\x10HealthPingConfig\x12\x13\n\x0b\x64\x65stination\x18\x01 \x01(\t\x12\x14\n\x0c\x63onnectivity\x18\x02 \x01(\t\x12\x10\n\x08interval\x18\x03 \x01(\x03\x12\x15\n\rsamplingCount\x18\x04 \x01(\x05\x12\x0f\n\x07timeout\x18\x05 \x01(\x03\x42\x81\x01\n$com.v2ray.core.app.observatory.burstP\x01Z4github.com/v2fly/v2ray-core/v5/app/observatory/burst\xaa\x02 V2Ray.Core.App.Observatory.Burstb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.observatory.burst.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.v2ray.core.app.observatory.burstP\001Z4github.com/v2fly/v2ray-core/v5/app/observatory/burst\252\002 V2Ray.Core.App.Observatory.Burst'
  _globals['_CONFIG']._options = None
  _globals['_CONFIG']._serialized_options = b'\202\265\030\033\n\007service\022\020burstObservatory'
  _globals['_CONFIG']._serialized_start=107
  _globals['_CONFIG']._serialized_end=247
  _globals['_HEALTHPINGCONFIG']._serialized_start=249
  _globals['_HEALTHPINGCONFIG']._serialized_end=368
# @@protoc_insertion_point(module_scope)
