# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from transport.internet import config_pb2 as transport_dot_internet_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16transport/config.proto\x12\x14v2ray.core.transport\x1a\x1ftransport/internet/config.proto\"X\n\x06\x43onfig\x12J\n\x12transport_settings\x18\x01 \x03(\x0b\x32..v2ray.core.transport.internet.TransportConfig:\x02\x18\x01\x42]\n\x18\x63om.v2ray.core.transportP\x01Z(github.com/v2fly/v2ray-core/v5/transport\xaa\x02\x14V2Ray.Core.Transportb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.v2ray.core.transportP\001Z(github.com/v2fly/v2ray-core/v5/transport\252\002\024V2Ray.Core.Transport'
  _globals['_CONFIG']._options = None
  _globals['_CONFIG']._serialized_options = b'\030\001'
  _globals['_CONFIG']._serialized_start=81
  _globals['_CONFIG']._serialized_end=169
# @@protoc_insertion_point(module_scope)
