# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/commander/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61pp/commander/config.proto\x12\x18v2ray.core.app.commander\x1a\x19google/protobuf/any.proto\x1a common/protoext/extensions.proto\"<\n\x06\x43onfig\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12%\n\x07service\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\"1\n\x10ReflectionConfig:\x1d\x82\xb5\x18\x19\n\x0bgrpcservice\x12\nreflection\"G\n\x10SimplifiedConfig\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x03(\t:\x18\x82\xb5\x18\x14\n\x07service\x12\tcommanderBi\n\x1c\x63om.v2ray.core.app.commanderP\x01Z,github.com/v2fly/v2ray-core/v5/app/commander\xaa\x02\x18V2Ray.Core.App.Commanderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.commander.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.v2ray.core.app.commanderP\001Z,github.com/v2fly/v2ray-core/v5/app/commander\252\002\030V2Ray.Core.App.Commander'
  _globals['_REFLECTIONCONFIG']._options = None
  _globals['_REFLECTIONCONFIG']._serialized_options = b'\202\265\030\031\n\013grpcservice\022\nreflection'
  _globals['_SIMPLIFIEDCONFIG']._options = None
  _globals['_SIMPLIFIEDCONFIG']._serialized_options = b'\202\265\030\024\n\007service\022\tcommander'
  _globals['_CONFIG']._serialized_start=117
  _globals['_CONFIG']._serialized_end=177
  _globals['_REFLECTIONCONFIG']._serialized_start=179
  _globals['_REFLECTIONCONFIG']._serialized_end=228
  _globals['_SIMPLIFIEDCONFIG']._serialized_start=230
  _globals['_SIMPLIFIEDCONFIG']._serialized_end=301
# @@protoc_insertion_point(module_scope)
