# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/observatory/multiobservatory/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.taggedfeatures import skeleton_pb2 as common_dot_taggedfeatures_dot_skeleton__pb2
from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-app/observatory/multiobservatory/config.proto\x12+v2ray.core.app.observatory.multiobservatory\x1a$common/taggedfeatures/skeleton.proto\x1a common/protoext/extensions.proto\"d\n\x06\x43onfig\x12\x39\n\x07holders\x18\x01 \x01(\x0b\x32(.v2ray.core.common.taggedfeatures.Config:\x1f\x82\xb5\x18\x1b\n\x07service\x12\x10multiobservatoryB\xa2\x01\n/com.v2ray.core.app.observatory.multiObservatoryP\x01Z?github.com/v2fly/v2ray-core/v5/app/observatory/multiobservatory\xaa\x02+V2Ray.Core.App.Observatory.MultiObservatoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.observatory.multiobservatory.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n/com.v2ray.core.app.observatory.multiObservatoryP\001Z?github.com/v2fly/v2ray-core/v5/app/observatory/multiobservatory\252\002+V2Ray.Core.App.Observatory.MultiObservatory'
  _globals['_CONFIG']._options = None
  _globals['_CONFIG']._serialized_options = b'\202\265\030\033\n\007service\022\020multiobservatory'
  _globals['_CONFIG']._serialized_start=166
  _globals['_CONFIG']._serialized_end=266
# @@protoc_insertion_point(module_scope)
