# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/request/assembly/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0transport/internet/request/assembly/config.proto\x12.v2ray.core.transport.internet.request.assembly\x1a common/protoext/extensions.proto\x1a\x19google/protobuf/any.proto\"w\n\x06\x43onfig\x12\'\n\tassembler\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12*\n\x0croundtripper\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x18\x82\xb5\x18\x14\n\ttransport\x12\x07requestB\xab\x01\n2com.v2ray.core.transport.internet.request.assemblyP\x01ZBgithub.com/v2fly/v2ray-core/v5/transport/internet/request/assembly\xaa\x02.V2Ray.Core.Transport.Internet.Request.Assemblyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.request.assembly.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2com.v2ray.core.transport.internet.request.assemblyP\001ZBgithub.com/v2fly/v2ray-core/v5/transport/internet/request/assembly\252\002.V2Ray.Core.Transport.Internet.Request.Assembly'
  _globals['_CONFIG']._options = None
  _globals['_CONFIG']._serialized_options = b'\202\265\030\024\n\ttransport\022\007request'
  _globals['_CONFIG']._serialized_start=161
  _globals['_CONFIG']._serialized_end=280
# @@protoc_insertion_point(module_scope)
