# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/httpupgrade/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+transport/internet/httpupgrade/config.proto\x12\x31v2ray.core.transport.internet.request.httpupgrade\x1a common/protoext/extensions.proto\"F\n\x06\x43onfig\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t: \x82\xb5\x18\x1c\n\ttransport\x12\x0bhttpupgrade\x90\xff)\x01\x42\x9c\x01\n-com.v2ray.core.transport.internet.httpupgradeP\x01Z=github.com/v2fly/v2ray-core/v5/transport/internet/httpupgrade\xaa\x02)V2Ray.Core.Transport.Internet.HttpUpgradeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.httpupgrade.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-com.v2ray.core.transport.internet.httpupgradeP\001Z=github.com/v2fly/v2ray-core/v5/transport/internet/httpupgrade\252\002)V2Ray.Core.Transport.Internet.HttpUpgrade'
  _globals['_CONFIG']._options = None
  _globals['_CONFIG']._serialized_options = b'\202\265\030\034\n\ttransport\022\013httpupgrade\220\377)\001'
  _globals['_CONFIG']._serialized_start=132
  _globals['_CONFIG']._serialized_end=202
# @@protoc_insertion_point(module_scope)
