# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/request/assembler/simple/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8transport/internet/request/assembler/simple/config.proto\x12\x36v2ray.core.transport.internet.request.assembler.simple\x1a common/protoext/extensions.proto\"\x9b\x02\n\x0c\x43lientConfig\x12\x16\n\x0emax_write_size\x18\x01 \x01(\x05\x12 \n\x18wait_subsequent_write_ms\x18\x02 \x01(\x05\x12#\n\x1binitial_polling_interval_ms\x18\x03 \x01(\x05\x12\x1f\n\x17max_polling_interval_ms\x18\x04 \x01(\x05\x12\x1f\n\x17min_polling_interval_ms\x18\x05 \x01(\x05\x12\x16\n\x0e\x62\x61\x63koff_factor\x18\x06 \x01(\x02\x12 \n\x18\x66\x61iled_retry_interval_ms\x18\x07 \x01(\x05:0\x82\xb5\x18,\n\"transport.request.assembler.client\x12\x06simple\"X\n\x0cServerConfig\x12\x16\n\x0emax_write_size\x18\x01 \x01(\x05:0\x82\xb5\x18,\n\"transport.request.assembler.server\x12\x06simpleB\xc3\x01\n:com.v2ray.core.transport.internet.request.assembler.simpleP\x01ZJgithub.com/v2fly/v2ray-core/v5/transport/internet/request/assembler/simple\xaa\x02\x36V2Ray.Core.Transport.Internet.Request.Assembler.Simpleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.request.assembler.simple.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n:com.v2ray.core.transport.internet.request.assembler.simpleP\001ZJgithub.com/v2fly/v2ray-core/v5/transport/internet/request/assembler/simple\252\0026V2Ray.Core.Transport.Internet.Request.Assembler.Simple'
  _globals['_CLIENTCONFIG']._options = None
  _globals['_CLIENTCONFIG']._serialized_options = b'\202\265\030,\n\"transport.request.assembler.client\022\006simple'
  _globals['_SERVERCONFIG']._options = None
  _globals['_SERVERCONFIG']._serialized_options = b'\202\265\030,\n\"transport.request.assembler.server\022\006simple'
  _globals['_CLIENTCONFIG']._serialized_start=151
  _globals['_CLIENTCONFIG']._serialized_end=434
  _globals['_SERVERCONFIG']._serialized_start=436
  _globals['_SERVERCONFIG']._serialized_end=524
# @@protoc_insertion_point(module_scope)
