# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/subscription/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61pp/subscription/config.proto\x12\x1bv2ray.core.app.subscription\x1a common/protoext/extensions.proto\"w\n\x0cImportSource\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x12\n\ntag_prefix\x18\x03 \x01(\t\x12\x18\n\x10import_using_tag\x18\x04 \x01(\t\x12\x1e\n\x16\x64\x65\x66\x61ult_expire_seconds\x18\x05 \x01(\x04\"\xd5\x01\n\x06\x43onfig\x12:\n\x07imports\x18\x01 \x03(\x0b\x32).v2ray.core.app.subscription.ImportSource\x12#\n\x1bnonnative_converter_overlay\x18\x02 \x01(\x0c\x12M\n nonnative_converter_overlay_file\x18\x82\xee\x05 \x01(\tB!\x82\xb5\x18\x1d\"\x1bnonnative_converter_overlay:\x1b\x82\xb5\x18\x17\n\x07service\x12\x0csubscriptionBr\n\x1f\x63om.v2ray.core.app.subscriptionP\x01Z/github.com/v2fly/v2ray-core/v5/app/subscription\xaa\x02\x1bV2Ray.Core.App.Subscriptionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.subscription.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.v2ray.core.app.subscriptionP\001Z/github.com/v2fly/v2ray-core/v5/app/subscription\252\002\033V2Ray.Core.App.Subscription'
  _globals['_CONFIG'].fields_by_name['nonnative_converter_overlay_file']._options = None
  _globals['_CONFIG'].fields_by_name['nonnative_converter_overlay_file']._serialized_options = b'\202\265\030\035\"\033nonnative_converter_overlay'
  _globals['_CONFIG']._options = None
  _globals['_CONFIG']._serialized_options = b'\202\265\030\027\n\007service\022\014subscription'
  _globals['_IMPORTSOURCE']._serialized_start=96
  _globals['_IMPORTSOURCE']._serialized_end=215
  _globals['_CONFIG']._serialized_start=218
  _globals['_CONFIG']._serialized_end=431
# @@protoc_insertion_point(module_scope)
