# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/net/packetaddr/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"common/net/packetaddr/config.proto\x12\x19v2ray.core.net.packetaddr*&\n\x0ePacketAddrType\x12\x08\n\x04None\x10\x00\x12\n\n\x06Packet\x10\x01\x42\x81\x01\n$com.v2ray.core.common.net.packetaddrP\x01Z4github.com/v2fly/v2ray-core/v5/common/net/packetaddr\xaa\x02 V2Ray.Core.Common.Net.Packetaddrb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.net.packetaddr.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.v2ray.core.common.net.packetaddrP\001Z4github.com/v2fly/v2ray-core/v5/common/net/packetaddr\252\002 V2Ray.Core.Common.Net.Packetaddr'
  _globals['_PACKETADDRTYPE']._serialized_start=65
  _globals['_PACKETADDRTYPE']._serialized_end=103
# @@protoc_insertion_point(module_scope)
