# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/request/roundtripper/httprt/config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;transport/internet/request/roundtripper/httprt/config.proto\x12\x39v2ray.core.transport.internet.request.roundtripper.httprt\x1a common/protoext/extensions.proto\"\x98\x01\n\x0c\x43lientConfig\x12S\n\x04http\x18\x01 \x01(\x0b\x32\x45.v2ray.core.transport.internet.request.roundtripper.httprt.HTTPConfig:3\x82\xb5\x18/\n%transport.request.roundtripper.client\x12\x06httprt\"\xb9\x01\n\x0cServerConfig\x12S\n\x04http\x18\x01 \x01(\x0b\x32\x45.v2ray.core.transport.internet.request.roundtripper.httprt.HTTPConfig\x12\x1f\n\x17no_decoding_session_tag\x18\x02 \x01(\x08:3\x82\xb5\x18/\n%transport.request.roundtripper.server\x12\x06httprt\"-\n\nHTTPConfig\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\turlPrefix\x18\x02 \x01(\tB\xcc\x01\n=com.v2ray.core.transport.internet.request.roundtripper.httprtP\x01ZMgithub.com/v2fly/v2ray-core/v5/transport/internet/request/roundtripper/httprt\xaa\x02\x39V2Ray.Core.Transport.Internet.Request.Roundtripper.httprtb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.request.roundtripper.httprt.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n=com.v2ray.core.transport.internet.request.roundtripper.httprtP\001ZMgithub.com/v2fly/v2ray-core/v5/transport/internet/request/roundtripper/httprt\252\0029V2Ray.Core.Transport.Internet.Request.Roundtripper.httprt'
  _globals['_CLIENTCONFIG']._options = None
  _globals['_CLIENTCONFIG']._serialized_options = b'\202\265\030/\n%transport.request.roundtripper.client\022\006httprt'
  _globals['_SERVERCONFIG']._options = None
  _globals['_SERVERCONFIG']._serialized_options = b'\202\265\030/\n%transport.request.roundtripper.server\022\006httprt'
  _globals['_CLIENTCONFIG']._serialized_start=157
  _globals['_CLIENTCONFIG']._serialized_end=309
  _globals['_SERVERCONFIG']._serialized_start=312
  _globals['_SERVERCONFIG']._serialized_end=497
  _globals['_HTTPCONFIG']._serialized_start=499
  _globals['_HTTPCONFIG']._serialized_end=544
# @@protoc_insertion_point(module_scope)
